### ISSUE TITLE
"u" RegExp flag prevents old systems to work

### ISSUE THREAD

**Issue by Llorx** [lddubeau/xmlchars#3]
What the title says. `u` flag is not implemented everywhere (ES2015 feature).
```
SyntaxError: Invalid flags supplied to RegExp constructor 'u'
```

There are transpilers that convert those unicode RegExp to "normal" ones. Like this one https://github.com/mathiasbynens/regexpu (Demo: https://mothereff.in/regexpu).

Babel don't has a transpiler for this, neither Typescript.

For example, this one:

    var a = new RegExp(/^[\t\n\r -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF]$/u);

is converted to this one:

    var a = new RegExp(/^(?:[\t\n\r -\uD7FF\uE000-\uFFFD]|[\uD800-\uDBFF][\uDC00-\uDFFF])$/);

Which works perfectly under a system without ES2015 `u` flag.

**Comment by Llorx** [comment]
Just found this: https://babeljs.io/docs/en/babel-plugin-proposal-unicode-property-regex

Maybe it can be "babelized".

**Comment by alubbe** [comment]
We fixed it like this: https://github.com/exceljs/exceljs/issues/1177#issuecomment-607207836

**Comment by lddubeau** [comment]
Right. Projects that consume this library and need to provide support for older platforms will have either to use polyfills or transpilers.

There is currently no plan to provide builds for "old platforms". I should update the README with some statement regarding this.
